name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - build  # Trigger deployment on push to 'build' branch
  workflow_dispatch:  # Optional: allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS support

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Unity Build
        uses: actions/upload-pages-artifact@v1
        with:
          path: './Build' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
