name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - build
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04  # Try a different runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          lfs: true

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Preload upload-artifact (workaround)
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
